pipeline {

    agent any

    environment {
        IMAGE_NAME = "ngk2026/devops-journey-p2"
        IMAGE_TAG = "latest"
        DOCKERHUB_CREDENTIALS = credentials('project2-dockerhub')
        
    }

    stages {

        stage("Build Docker image") {

            steps {
                sh "docker build -t ${IMAGE_NAME}:${IMAGE_TAG} ."
            }
        }

        stage("Push to DockerHub") {

            steps {
                sh "docker login -u ${DOCKERHUB_CREDENTIALS_USR} -p ${DOCKERHUB_CREDENTIALS_PSW}"
                sh "docker push ${IMAGE_NAME}:${IMAGE_TAG}"
            }
        }

        stage("Deploy to Kubernetes using Helm") {

            steps {
                sh "helm upgrade --install health-monitor-p2 ./health-monitor-p2 --set image.repository=${IMAGE_NAME} --set image.tag=${IMAGE_TAG}" 
            }
        }
    }
    post {
        success {
            echo 'Production Success !!!'
        }
        failure {
            echo 'Production Failure !!!'
        }
    }
}

