pipeline {

    agent any

    environment {
        IMAGE_NAME = "ngk2026/devops-journey-p2"
        IMAGE_TAG = "latest"
        DOCKERHUB_CREDENTIALS = credentials('project2-dockerhub')
        KUBECONFIG = "/var/jenkins_home/.kube/config" // helm automatically sees this and uses as reference
    }

    stages {

        stage("Build Docker image") {

            steps {
                sh "docker build -t ${IMAGE_NAME}:${IMAGE_TAG} ./projects/2-enterprise_health-monitor/"
            }
        }

        stage("Push to DockerHub") {

            steps {
                sh "docker login -u ${DOCKERHUB_CREDENTIALS_USR} -p ${DOCKERHUB_CREDENTIALS_PSW}"
                sh "docker push ${IMAGE_NAME}:${IMAGE_TAG}"
            }
        }

        stage("Deploy to Kubernetes using Helm") {

            steps {
                sh "helm upgrade --install health-monitor-p2 ./projects/2-enterprise_health-monitor/health-monitor-p2 --set image.repository=${IMAGE_NAME} --set image.tag=${IMAGE_TAG}" 
            }
        }
    }
    post {
        success {
            echo 'Production Success !!!'
        }
        failure {
            echo 'Production Failure !!!'
        }
    }
}

