pipeline {

    agent any
    
    environment {
        IMAGE_NAME = "ngk2026/devops-journey-p2"
        IMAGE_TAG = "latest"
        DOCKERHUB_CREDENTIALS = credentials('project2-dockerhub')
    }

    stages {

        stage("Build Docker image") {

            steps {
                //
            }
        }

        stage("Push to DockerHub") {

            steps {
                //
            }
        }

        stage("Deploy to Kubernetes using Helm") {

            steps {
                //
            }
        }
    }
}

