apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: health-monitor-p2
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: health-monitor-p2
  endpoints:
    - port: http
      path: /metrics