---
## ALL
# PKG UPDATES
- hosts: all
  become: true
  pre_tasks: 

  - name: update cache (centos)
    tags: always
    dnf:
      update_cache: true
    changed_when: false
    when: ansible_facts['distribution'] == "CentOS"

  - name: update cache (ubuntu)
    tags: always
    apt:
      update_cache: true
    changed_when: false
    when: ansible_facts['distribution'] == "Ubuntu"

  - name: update cache (archlinux)
    tags: always
    pacman:
      update_cache: true
    changed_when: false
    when: ansible_facts['distribution'] == "Archlinux"

# VOID USER
- hosts: all
  become: true
  tasks:

  - name: create void user
    tags: always
    user:
      name: void
      groups: root
  
  - name: add ssh key for void
    tags: always
    authorized_key:
      user: void
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINZV/VjSdJNEj5jcdZFz+fq6Nmticv2of6SgNNxlr+Xx ansible"

  - name: add sudoers file for void
    tags: always
    copy:
      src: sudoer_void
      dest: /etc/sudoers.d/void
      owner: root
      group: root
      mode: 0440

# CENTOS
# ADD REPO
  - name: add docker repo (centos)
    ansible.builtin.get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo
      mode: '0440'
    when: 
    - ansible_facts['distribution'] == "CentOS"  

# INSTALL DOCKER
  - name: install docker
    package:
      name: "{{ docker_packages }}"
      state: latest

# START DOCKER SERVICE
  - name: start docker service
    service:
      name: "{{ docker_service }}"
      state: started
      enabled: true

# INSTALL PYTHON REQUEST REQ 
  - name: install python requests 
    package:
      name: "{{ python_requests_package }}"
      state: present
    when: ansible_facts['distribution'] in ["Archlinux", "CentOS"]

# START JENKINS CONTAINER
  # - name: Start Jenkins container
  #   community.docker.docker_container:
  #     name: jenkins
  #     image: jenkins/jenkins
  #     state: started
  #     restart_policy: always
  #     network_mode: host
  #     volumes:
  #       - jenkins_home:/var/jenkins_home
  #       - /var/run/docker.sock:/var/run/docker.sock
  #       - /home/student/.minikube:/home/student/.minikube
  #     ports:
  #       - "8080:8080"
  #       - "50000:50000"
# COPY BASH SCRIPT ONTO UBUNTU
  - name: copy bash script install kube on UBUNTU
    copy:
      src: kube-ubuntu-install.sh
      dest: /home/student/kube-ubuntu-install.sh
      mode: 0755
    when: 
    - ansible_facts['distribution'] == "Ubuntu"  
# EXECUTE BASH
  - name: run kube install script
    shell: /home/student/kube-ubuntu-install.sh
    when: 
    - ansible_facts['distribution'] == "Ubuntu"