---
## ALL
# PKG UPDATES
- hosts: all
  become: true
  pre_tasks: 

  - name: update cache (centos)
    tags: always
    dnf:
      update_cache: true
    changed_when: false
    when: ansible_facts['distribution'] == "CentOS"

  - name: update cache (ubuntu)
    tags: always
    apt:
      update_cache: true
    changed_when: false
    when: ansible_facts['distribution'] == "Ubuntu"

  - name: update cache (archlinux)
    tags: always
    pacman:
      update_cache: true
    changed_when: false
    when: ansible_facts['distribution'] == "Archlinux"

# VOID USER
- hosts: all
  become: true
  tasks:

  - name: create void user
    tags: always
    user:
      name: void
      groups: root
  
  - name: add ssh key for void
    tags: always
    authorized_key:
      user: void
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINZV/VjSdJNEj5jcdZFz+fq6Nmticv2of6SgNNxlr+Xx ansible"

  - name: add sudoers file for void
    tags: always
    copy:
      src: sudoer_void
      dest: /etc/sudoers.d/void
      owner: root
      group: root
      mode: 0440

# CENTOS
# ADD REPO
  - name: add docker repo (centos)
    ansible.builtin.get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo
      mode: '0440'
    when: 
    - ansible_facts['distribution'] == "CentOS"  

# INSTALL DOCKER
  - name: install docker
    package:
      name: "{{ docker_packages }}"
      state: latest

# START DOCKER SERVICE
  - name: start docker service
    service:
      name: "{{ docker_service }}"
      state: started
      enabled: true

# INSTALL PYTHON REQUEST REQ 
  - name: install python requests 
    package:
      name: "{{ python_requests_package }}"
      state: present
    when: ansible_facts['distribution'] in ["Archlinux", "CentOS"]

# START JENKINS CONTAINER
  # - name: Start Jenkins container
  #   community.docker.docker_container:
  #     name: jenkins
  #     image: jenkins/jenkins
  #     state: started
  #     restart_policy: always
  #     network_mode: host
  #     volumes:
  #       - jenkins_home:/var/jenkins_home
  #       - /var/run/docker.sock:/var/run/docker.sock
  #       - /home/student/.minikube:/home/student/.minikube
  #     ports:
  #       - "8080:8080"
  #       - "50000:50000"

# INSTALL KUBERNETES 
# UBUNTU
# REQUIREMENTS
  - name: install repository prerequisites (Ubuntu)
    apt:
      name:
        - gnupg
        - software-properties-common
        - ca-certificates
        - curl
        - apt-transport-https
      state: present
      update_cache: true
    when:
      - ansible_facts['distribution'] == "Ubuntu"
      - ansible_facts['distribution_major_version'] in ["22", "26"]
# MKDIR keyrings
  - name: create keyrings dir
    file:
      path: /etc/apt/keyrings
      state: directory
      mode: '0755'
    when:
      - ansible_facts['distribution'] == "Ubuntu"
      - ansible_facts['distribution_major_version'] in ["22", "26"]
# GPG
  - name: add kubernetes GPG (ubuntu)
    ansible.builtin.get_url:
      url: https://pkgs.k8s.io/core:/stable:/v1.36/deb/Release.key
      dest: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      mode: '0644'
    when:
      - ansible_facts['distribution'] == "Ubuntu"
      - ansible_facts['distribution_major_version'] in ["22", "26"]
# UPDATE CACHE
  - name: update apt cache before adding repo
    apt:
      update_cache: true
      cache_valid_until: 24h
    when:
      - ansible_facts['distribution'] == "Ubuntu"
      - ansible_facts['distribution_major_version'] in ["22", "26"]
# REPO
  - name: add kubernetes repo (ubuntu)
    ansible.builtin.apt_repository:
      repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.36/deb/ {{ ansible_distribution_release }} main"
      filename: kubernetes-1.36
      state: present
    when:
      - ansible_facts['distribution'] == "Ubuntu"
      - ansible_facts['distribution_major_version'] in ["22", "26"]
# INSTALL KUBERNETES
  - name: install kubernetes
    apt:
      name:
        - kubelet
        - kubeadm
        - kubectl
      state: present
    when: 
      - ansible_facts['distribution'] == "Ubuntu"
      - ansible_facts['distribution_major_version'] in ["22", "26"]
# START SERVICE
  - name: start kubernetes service
    service:
      name: kubelet
      state: started
      enabled: true
    when: 
      - ansible_facts['distribution'] == "Ubuntu"
      - ansible_facts['distribution_major_version'] in ["22", "26"]
  
