global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']


# exmaple job for node_exporter
  - job_name: 'node_exporter'
    static_configs:
     - targets: ['node_exporter:9100']
    # Use the host's IP address because node_exporter is in 'host' mode
    # - targets: ['host.docker.internal:9100']

# example job for cadvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']