apiVersion: apps/v1
kind: Deployment
metadata: # metadata contains labels
  name: nginx-deployment
  labels:
    app: nginx # deployment lable
spec: # of deployment / specs contain selectors
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template: # of pods
    metadata:
      labels:
        app: nginx # connect this pod to same deployment lable
    spec: # blue print of pod
      containers:
      - name: nginx
        image: nginx:1.16
        ports:
        - containerPort: 8080 # should match service target port
