---

- hosts: all
  become: true
  tasks:

  - name: update index and install apache2 and php package for ubuntu
    apt:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: true



