name: CI Pipeline

on:
  push:
    branches: ["main"]
    paths:
      - 'projects/health-monitor/Dockerfile'
      - 'projects/health-monitor/app/app.py'
      - '.github/workflows/health-monitor.yml'
      # - '!projects/health-monitor/README.md' # ignore #

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push
      uses: docker/build-push-action@v7
      with:
        context: ./projects/health-monitor
        push: true
        tags: ngk2026/health-monitor:latest
        no-cache: true # # #
    
    - name: ssh and deploy
      env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER_NAME: ${{ secrets.USER_NAME }}

      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOST} '

            cd /home/ec2-user/devops-journey/projects/health-monitor
            docker stop $(docker ps -q)
            docker pull ngk2026/health-monitor:latest
            docker run -d --name health-monitor -p 5000:5000 ngk2026/health-monitor:latest 
            docker start prometheus grafana
            '
